name: domain
description: Domain Module
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # This is our modular
  dependencies:
    path: "../dependencies"
  commons:
    path: "../commons" 

  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable:

flutter:
